const ETHEREUM_STATUS = {
  UNCHECKED: Symbol('ETHEREUM_UNCHECKED'),
  CHECKING: Symbol('ETHEREUM_CHECKING'),
  SUCCESS: Symbol('ETHEREUM_SUCCESS'),
  ERROR: Symbol('ETHEREUM_ERROR')
}

Object.freeze(ETHEREUM_STATUS)

export default ETHEREUM_STATUS
