const STATUS = {
  PENDING_IPFS: Symbol('PENDING_IPFS'),
  PENDING_APPROVAL: Symbol('PENDING_APPROVAL'),
  PENDING_TX: Symbol('PENDING_TX'),
  MOD_PENDING_APPROVAL: Symbol('MOD_PENDING_APPROVAL'),
  MOD_PENDING_TX: Symbol('MOD_PENDING_TX'),
  ERROR: Symbol('ERROR'),
  SAVED: Symbol('SAVED')
}
Object.freeze(STATUS)

export default STATUS
